
const dict = {
    us2g:{
    general: ['point_of_interest', 'establishment','premise'],
    food: ['food', 'restaurant'],
    shopping: ['supermarket', 'shopping_mall', 'store'],
    nature: ['natural_feature'],
    nightlife: ['bar', 'nightclub'],
    park: ['park'],
    artnhistory: ['museum', 'art_gallery']
},
    g2us: {
        point_of_interest: 'general',
        establishment: 'general',
        museum: 'artnhistory',
        shopping_mall: 'shopping',
        park: 'park',
        supermarket: 'shopping',
        grocery_or_supermarket: 'shopping',
        food: 'food',
        store: 'shopping',
        natural_feature: 'nature',
        bar: 'nightlife',
        restaurant: 'food',
        night_club: 'nightlife',
        premise: 'general'
    },
    int2ext: {
        general: 'Must See and Do',
        food: 'Food',
        shopping: 'Shopping',
        nature: 'Nature',
        nightlife: 'Nightlife',
        park: 'Parks',
        artnhistory: 'Culture'
    },
    images:  {
        general: require('../assets/general.jpg'),
        food: require('../assets/food.jpg'),
        shopping: require('../assets/shopping.jpg'),
        nature: require('../assets/nature.jpg'),
        nightlife: require('../assets/nightlife.jpg'),
        park: require('../assets/park.jpg'),
        artnhistory: require('../assets/artnhistory.jpg'),
    },
    languages: {
        default: 'Choose your language',
        af: 'Afrikaans',
        sq:'Albanian',
        am:'Amharic',
        ar:'Arabic',
        hy:'Armenian',
        az:'Azerbaijani',
        eu:'Basque',
        be:'Belarusian',
        bn:'Bengali',
        bs:'Bosnian',
        bg:'Bulgarian',
        ca:'Catalan',
        ceb:'Cebuano',
        "zh-CN":'Chinese (Simplified)',
        "zh-TW":'Chinese (Traditional)',
        co:'Corsican',
        hr:'Croatian',
        cs:'Czech',
        da:'Danish',
        nl:'Dutch',
        en:'English',
        eo:'Esperanto',
        et:'Estonian',
        fi:'Finnish',
        fr:'French',
        fy:'Frisian',
        gl:'Galician',
        ka:'Georgian',
        de:'German',
        el:'Greek',
        gu:'Gujarati',
        ht:'Haitian Creole',
        ha:'Hausa',
        haw:'Hawaiian',
        he:'Hebrew',
        hi:'Hindi',
        hmn:'Hmong',
        hu:'Hungarian',
        is:'Icelandic',
        ig:'Igbo',
        id:'Indonesian',
        ga:'Irish',
        it:'Italian',
        ja:'Japanese',
        jw:'Javanese',
        kn:'Kannada',
        kk:'Kazakh',
        km:'Khmer',
        ko:'Korean',
        ku:'Kurdish',
        ky:'Kyrgyz',
        lo:'Lao',
        la:'Latin',
        lv:'Latvian',
        lt:'Lithuanian',
        lb:'Luxembourgish',
        mk:'Macedonian',
        mg:'Malagasy',
        ms:'Malay',
        ml:'Malayalam',
        mt:'Maltese',
        mi:'Maori',
        mr:'Marathi',
        mn:'Mongolian',
        my:'Myanmar (Burmese)',
        ne:'Nepali',
        no:'Norwegian',
        ny:'Nyanja (Chichewa)',
        ps:'Pashto',
        fa:'Persian',
        pl:'Polish',
        pt:'Portuguese',
        pa:'Punjabi',
        ro:'Romanian',
        ru:'Russian',
        sm:'Samoan',
        gd:'Scots Gaelic',
        sr:'Serbian',
        st:'Sesotho',
        sn:'Shona',
        sd:'Sindhi',
        si:'Sinhala (Sinhalese)',
        sk:'Slovak',
        sl:'Slovenian',
        so:'Somali',
        es:'Spanish',
        su:'Sundanese',
        sw:'Swahili',
        sv:'Swedish',
        tl:'Tagalog (Filipino)',
        tg:'Tajik',
        ta:'Tamil',
        te:'Telugu',
        th:'Thai',
        tr:'Turkish',
        uk:'Ukrainian',
        ur:'Urdu',
        uz:'Uzbek',
        vi:'Vietnamese',
        cy:'Welsh',
        xh:'Xhosa',
        yi:'Yiddish',
        yo:'Yoruba',
        zu:'Zulu',
    },

}
export default dict;