import {StyleSheet,Dimensions} from 'react-native';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window')
const styles = StyleSheet.create({
    itemElement: {
      flex: 1,
      backgroundColor: "rgba(252, 177, 48,1)",
      padding:30,
      marginTop:20,
      alignItems:"center",
      borderRadius: 20,
      borderColor: 'grey',
      borderWidth: 1,
      marginHorizontal: 20,
      borderTopColor: "rgba(29, 72, 134,1)",
      borderTopWidth: 100/2,
//      borderTopWidth: 100,
//      borderRightWidth: 100/2,
      borderRightColor: 'transparent',
    },
    itemElement_bicolor: {
      flex: 1,
      backgroundColor: "rgba(29, 72, 134,1)",
      padding:20,
      marginTop:20,
      marginHorizontal: 20,
      alignItems:"center",
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      borderBottomLeftRadius: 20,
      borderBottomRightRadius: 20,
      borderTopColor: "rgba(252, 177, 48,1)",
      borderTopWidth: SCREEN_HEIGHT/15,
      borderBottomColor: "rgba(252, 177, 48,1)",
      borderBottomWidth: SCREEN_HEIGHT/15,
      borderRightColor: "rgba(252, 177, 48,1)",
      borderRightWidth: SCREEN_WIDTH/5,
      borderLeftColor: "rgba(252, 177, 48,1)",
      borderLeftWidth: SCREEN_WIDTH/5,
      borderRightColor: 'transparent',
    },
    itemElementdetail: {
      flex: 1,
      backgroundColor: "rgba(29, 72, 134,1)",
      padding:30,
      marginTop:20,
      alignItems:"center",
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      borderColor: 'grey',
      borderBottomColor:'rgba(29, 72, 134,1)',
      borderBottomWidth: 1,
      borderLeftWidth: 1,
      borderRightWidth: 1,
      borderTopWidth: 1,
      marginHorizontal: 20,
    },
    recElement: {
      flex: 1,
      backgroundColor: "rgba(252, 177, 48,0.95)",
      paddingVertical:25,
      paddingHorizontal:15,
      justifyContent:'space-between',
      borderBottomWidth:1,
//      borderBottomColor:'lightblue',
      borderBottomLeftRadius: 20,
      borderBottomRightRadius: 20,
      fontSize : 10,
      opacity: 1,
      fontWeight: 'bold',
      borderColor: 'grey',
      borderTopColor:'rgba(252, 177, 48,0.95)',
      borderTopWidth: 1,
      borderLeftWidth: 1,
      borderRightWidth: 1,
      borderBottomWidth: 1,
      marginHorizontal: 20,
    },
    textElementHome: {
      fontSize : 20,
      opacity: 1,
      fontWeight: 'bold',
      color: 'white'
    },
    textElement: {
      fontSize : 20,
      opacity: 1,
      fontWeight: 'bold',
      color: 'white'
    },
    textRecElement: {
      fontSize : 16,
      opacity: 1,
      alignSelf: 'flex-end',
      fontWeight: 'bold',
      textAlign: 'right',
      color: 'white'
    },
    listElements: {
      flex: 1,
      paddingTop:20,
      justifyContent:"center",
      alignItems:"center"
    },
    listRecomandationPage: {
      flex: 1,
      margin:50,
      justifyContent:"center",
    },
    textInput: {
      fontSize: 28,
      flex: 1,
      backgroundColor: "rgba(252, 177, 48,0.95)",
      alignItems:"center",
      textAlign:"center",
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      borderBottomLeftRadius: 20,
      borderBottomRightRadius: 20,
//      borderColor: 'grey',
      borderBottomWidth: 1,
      borderLeftWidth: 1,
      borderRightWidth: 1,
      borderTopWidth: 1,
      borderTopColor: "rgba(29, 72, 134,1)",
      borderTopWidth: 100/2,
      color: 'white'
    },
    textSuggest: {
      height: 50,
      fontSize: 18,
      margin: 5,
    },
    suggestElement: {
      borderColor: '#CCCCCC',
      alignItems:"center",
      textAlign:"center",
      borderTopLeftRadius: 15,
      borderTopRightRadius: 15,
      borderBottomLeftRadius: 15,
      borderBottomRightRadius: 15,
      borderColor: 'grey',
      borderBottomWidth: 1,
      borderLeftWidth: 1,
      borderRightWidth: 1,
      borderTopWidth: 1,
      backgroundColor:"lightgrey",
      height: 50,
      fontSize: 18,
      margin: 5
    },
    homeElement: {
      flex: 1,
      paddingTop:20,
      alignItems:"center",
    },
    itemElementHometop: {
      backgroundColor: "rgba(29, 72, 134,1)",
      padding:30,
      marginTop:0,
      marginHorizontal:0,
      alignItems:"center",
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      borderBottomLeftRadius: 20,
      borderBottomRightRadius: 20,
      borderColor:'rgba(29, 72, 134,1)',
      borderBottomWidth: 1,
      borderLeftWidth: 1,
      borderRightWidth: 1,
      borderTopWidth: 1,
//      marginHorizontal: 20,
    },
    itemElementHomebottom: {
      backgroundColor: "rgba(252, 177, 48,0.95)",
      padding:30,
      marginTop:20,
      alignItems:"center",
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      borderBottomLeftRadius: 20,
      borderBottomRightRadius: 20,
      borderColor: 'rgba(252, 177, 48,0.95)',
      borderBottomWidth: 1,
      borderLeftWidth: 1,
      borderRightWidth: 1,
      borderTopWidth: 1,
//      justifyContent:'space-between',
    },
    itemElementHomesubBottom: {
      backgroundColor: 'transparent',
      padding:10,
      marginTop:20,
      alignItems:"center",
      justifyContent:'space-between',
    },
    bkgImage: {
      width: '100%',
      height: '100%',
    },
    bottomView:{
      width: '100%',
      height: 50,
      backgroundColor: '#FF9800',
      justifyContent: 'center',
      alignItems: 'center',
      position: 'absolute',
      bottom: 0
    },
  })

  export default styles
